[2024-07-10T19:19:12.800+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:19:12.813+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:19:12.816+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:19:12.848+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:19:12.885+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-07-10T19:19:12.888+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpoh7atrx6']
[2024-07-10T19:19:12.895+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask film_category
[2024-07-10T19:19:13.076+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 988357c0810b
[2024-07-10T19:19:14.785+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:19:14.797+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'SqlToStaging'
[2024-07-10T19:19:14.823+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)['tabletype'].values[0]
  File "/opt/airflow/dags/dag.py", line 30, in get_data_from_conf_table
    cur.execute(query)
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'execute'
[2024-07-10T19:19:14.840+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T191912, end_date=20240710T191914
[2024-07-10T19:19:14.848+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task film_category ('psycopg2.extensions.connection' object has no attribute 'execute'; 94)
[2024-07-10T19:19:14.892+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:19:14.909+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:24:52.075+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:24:52.101+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:24:52.103+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:24:52.171+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:24:52.180+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-10T19:24:52.187+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpt6q2q0su']
[2024-07-10T19:24:52.199+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film_category
[2024-07-10T19:24:52.374+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 1dd842c603c2
[2024-07-10T19:24:53.665+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:24:53.670+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'SqlToStaging'
[2024-07-10T19:24:53.700+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)['tabletype'].values[0]
  File "/opt/airflow/dags/dag.py", line 34, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T19:24:53.717+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T192452, end_date=20240710T192453
[2024-07-10T19:24:53.730+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 95)
[2024-07-10T19:24:53.758+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:24:53.847+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:33:52.776+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:33:52.789+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:33:52.795+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:33:52.817+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:33:52.829+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-10T19:33:52.858+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjtswhdgv']
[2024-07-10T19:33:52.871+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask film_category
[2024-07-10T19:33:52.987+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host a0982d156a38
[2024-07-10T19:33:54.119+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:33:54.131+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'SqlToStaging'
[2024-07-10T19:33:54.154+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)
  File "/opt/airflow/dags/dag.py", line 34, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T19:33:54.178+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T193352, end_date=20240710T193354
[2024-07-10T19:33:54.211+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 98)
[2024-07-10T19:33:54.295+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:33:54.426+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:37:48.044+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:37:48.067+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:37:48.072+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:37:48.133+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:37:48.157+0000] {standard_task_runner.py:60} INFO - Started process 236 to run task
[2024-07-10T19:37:48.163+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp25owk0wo']
[2024-07-10T19:37:48.173+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask film_category
[2024-07-10T19:37:48.322+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host a0982d156a38
[2024-07-10T19:37:48.455+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:37:48.463+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T19:37:49.362+0000] {logging_mixin.py:188} INFO -    0              1          2       3   ...    11    12            13    14
0  14  film_category  dvdrental  public  ...  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:37:49.389+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T19:37:49.394+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:37:49.396+0000] {logging_mixin.py:188} INFO - table: film_category
[2024-07-10T19:37:49.399+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_category
[2024-07-10T19:37:49.401+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:37:49.436+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T193748, end_date=20240710T193749
[2024-07-10T19:37:49.544+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:37:49.638+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:39:58.338+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:39:58.356+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:39:58.360+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:39:58.413+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:39:58.427+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-10T19:39:58.450+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdkrw_c7m']
[2024-07-10T19:39:58.455+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask film_category
[2024-07-10T19:39:58.609+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 4118dead3d7f
[2024-07-10T19:39:59.945+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:39:59.948+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T19:40:00.006+0000] {logging_mixin.py:188} INFO -    0              1          2       3   ...    11    12            13    14
0  14  film_category  dvdrental  public  ...  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:40:00.015+0000] {logging_mixin.py:188} INFO - incremental
[2024-07-10T19:40:00.020+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:40:00.033+0000] {logging_mixin.py:188} INFO - table: film_category
[2024-07-10T19:40:00.044+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_category
[2024-07-10T19:40:00.046+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:40:00.061+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T193958, end_date=20240710T194000
[2024-07-10T19:40:00.137+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:40:00.157+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:44:03.084+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:44:03.157+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:44:03.166+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:44:03.284+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:44:03.296+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-10T19:44:03.316+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpb2f66mh8']
[2024-07-10T19:44:03.351+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film_category
[2024-07-10T19:44:03.595+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host a383c1e8c871
[2024-07-10T19:44:04.542+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:44:04.560+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T19:44:04.699+0000] {logging_mixin.py:188} INFO -    0              1          2       3   ...    11    12            13    14
0  14  film_category  dvdrental  public  ...  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:44:04.711+0000] {logging_mixin.py:188} INFO - incremental
[2024-07-10T19:44:04.727+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:44:04.738+0000] {logging_mixin.py:188} INFO - table: film_category
[2024-07-10T19:44:04.741+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_category
[2024-07-10T19:44:04.746+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:44:04.780+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T194403, end_date=20240710T194404
[2024-07-10T19:44:04.917+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:44:05.023+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:53:56.862+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:53:56.879+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:53:56.886+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:53:56.919+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:53:56.923+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2024-07-10T19:53:56.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplombmnrc']
[2024-07-10T19:53:56.950+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask film_category
[2024-07-10T19:53:57.108+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host c340805483c7
[2024-07-10T19:53:58.146+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:53:58.204+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:53:58.214+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T195356, end_date=20240710T195358
[2024-07-10T19:53:58.344+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:53:58.383+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:56:46.578+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:56:46.592+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:56:46.594+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:56:46.626+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:56:46.634+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-07-10T19:56:46.646+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpe9uwm6d5']
[2024-07-10T19:56:46.664+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask film_category
[2024-07-10T19:56:46.879+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host eb5f087f7265
[2024-07-10T19:56:47.738+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:56:47.891+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:56:47.954+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T195646, end_date=20240710T195647
[2024-07-10T19:56:48.081+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:56:48.156+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:00:56.803+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:00:56.825+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:00:56.835+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:00:56.936+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:00:56.950+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-10T20:00:56.993+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxb78qb0d']
[2024-07-10T20:00:57.007+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask film_category
[2024-07-10T20:00:57.202+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host c8649e4aae44
[2024-07-10T20:01:01.035+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:01:01.327+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
TypeError: some_function() missing 4 required positional arguments: 'schema', 'table', 'fromDate', and 'toDate'
[2024-07-10T20:01:01.368+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T200056, end_date=20240710T200101
[2024-07-10T20:01:01.472+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task film_category (some_function() missing 4 required positional arguments: 'schema', 'table', 'fromDate', and 'toDate'; 99)
[2024-07-10T20:01:01.549+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:01:01.753+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:05:21.200+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:05:21.221+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:05:21.229+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:05:21.271+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:05:21.282+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T20:05:21.300+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqumqpk8t']
[2024-07-10T20:05:21.312+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask film_category
[2024-07-10T20:05:21.486+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 3f026d601c5c
[2024-07-10T20:05:22.608+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:05:22.641+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'sqltostaging' and Stage = 'film_category'
[2024-07-10T20:05:22.671+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 45, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 145, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T20:05:22.684+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T200521, end_date=20240710T200522
[2024-07-10T20:05:22.724+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 96)
[2024-07-10T20:05:22.772+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:05:22.806+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:09:18.546+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:09:18.566+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:09:18.578+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:09:18.729+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:09:18.741+0000] {standard_task_runner.py:60} INFO - Started process 100 to run task
[2024-07-10T20:09:18.751+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzfg4hn2e']
[2024-07-10T20:09:18.772+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask film_category
[2024-07-10T20:09:19.150+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 61a58fe9b448
[2024-07-10T20:09:19.480+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:09:20.268+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:09:20.338+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:09:20.339+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 48, in getDF
    return pd.read_sql(query ,conn.getConnection(source_dbname))
AttributeError: module 'myFramework.source.posgresql.connect' has no attribute 'getConnection'
[2024-07-10T20:09:20.348+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T200918, end_date=20240710T200920
[2024-07-10T20:09:20.360+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task film_category (module 'myFramework.source.posgresql.connect' has no attribute 'getConnection'; 100)
[2024-07-10T20:09:20.378+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:09:20.474+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:15:06.658+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:15:06.675+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:15:06.679+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:15:06.702+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:15:06.726+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T20:15:06.736+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_f_qo4vz']
[2024-07-10T20:15:06.746+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask film_category
[2024-07-10T20:15:06.908+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host c782b552e7b5
[2024-07-10T20:15:08.321+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:15:08.350+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:15:08.440+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:15:08.446+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.film_category T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:15:08.512+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
[2024-07-10T20:15:08.541+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T201506, end_date=20240710T201508
[2024-07-10T20:15:08.587+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 3 elements; 96)
[2024-07-10T20:15:08.621+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:15:08.683+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:19:53.431+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:19:53.459+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:19:53.463+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:19:53.502+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:19:53.520+0000] {standard_task_runner.py:60} INFO - Started process 91 to run task
[2024-07-10T20:19:53.537+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsn9_q7up']
[2024-07-10T20:19:53.550+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask film_category
[2024-07-10T20:19:53.722+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host dcd5a91c9a96
[2024-07-10T20:19:54.440+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:19:54.987+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:19:55.057+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:19:55.058+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.film_category T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:19:55.158+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
[2024-07-10T20:19:55.183+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T201953, end_date=20240710T201955
[2024-07-10T20:19:55.194+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 3 elements; 91)
[2024-07-10T20:19:55.222+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:19:55.265+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:25:52.126+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:25:52.159+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:25:52.168+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:25:52.221+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:25:52.247+0000] {standard_task_runner.py:60} INFO - Started process 128 to run task
[2024-07-10T20:25:52.264+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmph_8ij5wa']
[2024-07-10T20:25:52.275+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film_category
[2024-07-10T20:25:52.523+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host d72f5bf26a9d
[2024-07-10T20:25:53.249+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:25:53.385+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:25:53.535+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:25:53.546+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.film_category T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:25:53.829+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
[2024-07-10T20:25:53.871+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T202552, end_date=20240710T202553
[2024-07-10T20:25:53.894+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 3 elements; 128)
[2024-07-10T20:25:53.937+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:25:54.009+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:33:41.823+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:33:41.843+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:33:41.863+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:33:41.879+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:33:41.918+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-10T20:33:41.929+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkerh8rrf']
[2024-07-10T20:33:41.951+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask film_category
[2024-07-10T20:33:42.123+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host d0a0151057b2
[2024-07-10T20:33:43.284+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:33:43.349+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:33:43.428+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:33:43.429+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.film_category T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:33:43.547+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
[2024-07-10T20:33:43.577+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T203341, end_date=20240710T203343
[2024-07-10T20:33:43.618+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task film_category (Length mismatch: Expected axis has 0 elements, new values have 3 elements; 97)
[2024-07-10T20:33:43.674+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:33:43.704+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:36:57.509+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:36:57.537+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:36:57.539+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:36:57.561+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:36:57.575+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-10T20:36:57.586+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxseoc58t']
[2024-07-10T20:36:57.591+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask film_category
[2024-07-10T20:36:57.843+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host dca83dd4e715
[2024-07-10T20:36:58.802+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:36:58.972+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:36:59.124+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:36:59.135+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.film_category T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:36:59.251+0000] {logging_mixin.py:188} INFO - not data at the period
[2024-07-10T20:36:59.273+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 63, in some_function
    if sourceDF is not None:
UnboundLocalError: local variable 'sourceDF' referenced before assignment
[2024-07-10T20:36:59.351+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T203657, end_date=20240710T203659
[2024-07-10T20:36:59.437+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task film_category (local variable 'sourceDF' referenced before assignment; 98)
[2024-07-10T20:36:59.499+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:36:59.600+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:40:13.941+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:40:13.957+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:40:13.968+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:40:14.012+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:40:14.033+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-07-10T20:40:14.043+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprgop35rj']
[2024-07-10T20:40:14.050+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask film_category
[2024-07-10T20:40:14.267+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 2bc01acfbd3e
[2024-07-10T20:40:15.459+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:40:15.488+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'sqltostaging'
[2024-07-10T20:40:15.549+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  14   film_category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:40:15.552+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.film_category T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:40:15.578+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T20:40:15.593+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_category, execution_date=20240709T000000, start_date=20240710T204013, end_date=20240710T204015
[2024-07-10T20:40:15.650+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T20:40:15.689+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
