[2024-07-10T20:28:09.337+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city manual__2024-07-10T20:28:06.951158+00:00 [queued]>
[2024-07-10T20:28:09.370+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city manual__2024-07-10T20:28:06.951158+00:00 [queued]>
[2024-07-10T20:28:09.378+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:28:09.439+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-10 20:28:06.951158+00:00
[2024-07-10T20:28:09.448+0000] {standard_task_runner.py:60} INFO - Started process 207 to run task
[2024-07-10T20:28:09.457+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'manual__2024-07-10T20:28:06.951158+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjviuj9qf']
[2024-07-10T20:28:09.468+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask city
[2024-07-10T20:28:09.856+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city manual__2024-07-10T20:28:06.951158+00:00 [running]> on host d72f5bf26a9d
[2024-07-10T20:28:10.193+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T20:28:06.951158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T20:28:06.951158+00:00'
[2024-07-10T20:28:10.229+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'city' and Stage = 'sqltostaging'
[2024-07-10T20:28:10.931+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   5            city    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:28:10.938+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:28:10.961+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240710T202806, start_date=20240710T202809, end_date=20240710T202810
[2024-07-10T20:28:10.990+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task city (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 207)
[2024-07-10T20:28:11.023+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:28:11.048+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
