[2024-07-02T18:42:24.363+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:42:24.373+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:42:24.375+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T18:42:24.402+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T18:42:24.417+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-07-02T18:42:24.424+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwy6xc2w8']
[2024-07-02T18:42:24.441+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film
[2024-07-02T18:42:24.578+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 5b7251376729
[2024-07-02T18:42:26.066+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T18:42:26.067+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: process_table() missing 1 required positional argument: 'table_type'
[2024-07-02T18:42:26.081+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T184224, end_date=20240702T184226
[2024-07-02T18:42:26.142+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task film (process_table() missing 1 required positional argument: 'table_type'; 92)
[2024-07-02T18:42:26.159+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T18:42:26.173+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T18:50:28.358+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:50:28.393+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:50:28.395+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T18:50:28.470+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T18:50:28.485+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcdk_5qlt']
[2024-07-02T18:50:28.489+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film
[2024-07-02T18:50:28.475+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-02T18:50:28.619+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host e236fd1115af
[2024-07-02T18:50:29.622+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T18:50:29.627+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T18:50:29.628+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T18:50:29.633+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T18:50:30.103+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T18:50:30.116+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T185028, end_date=20240702T185030
[2024-07-02T18:50:30.166+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T18:50:30.179+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:20:13.085+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:20:13.107+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:20:13.114+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:20:13.143+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:20:13.159+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-02T20:20:13.186+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_sj2u0p4']
[2024-07-02T20:20:13.205+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask film
[2024-07-02T20:20:13.394+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 881b4526a2de
[2024-07-02T20:20:15.002+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:20:15.009+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:20:15.015+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:20:15.017+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:20:15.038+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 29, in some_function
    print(get_data_from_conf_table("staff", "SqlToStaging"))
  File "/app/myFramework/utils/utils.py", line 137, in get_data_from_conf_table
    cur = conn.getCursor("Postgres")
  File "/app/myFramework/source/posgresql/connect.py", line 6, in getCursor
    conn = psycopg2.connect(database = dbname,
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres_db" (172.20.0.3), port 9999 failed: FATAL:  database "Postgres" does not exist

[2024-07-02T20:20:15.050+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T202013, end_date=20240702T202015
[2024-07-02T20:20:15.096+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task film (connection to server at "postgres_db" (172.20.0.3), port 9999 failed: FATAL:  database "Postgres" does not exist
; 95)
[2024-07-02T20:20:15.138+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:20:15.214+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:22:14.227+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:22:14.249+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:22:14.256+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:22:14.299+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:22:14.315+0000] {standard_task_runner.py:60} INFO - Started process 101 to run task
[2024-07-02T20:22:14.329+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpoly_wnx_']
[2024-07-02T20:22:14.344+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film
[2024-07-02T20:22:14.466+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host b2ca66e4d1f6
[2024-07-02T20:22:16.142+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:22:16.164+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:22:16.167+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:22:16.167+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:22:16.249+0000] {logging_mixin.py:188} INFO -    0      1          2       3     4   ...    10    11    12            13    14
0   9  staff  dvdrental  public  full  ...  None  None  None  SqlToStaging  None

[1 rows x 15 columns]
[2024-07-02T20:22:16.251+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:22:16.260+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T202214, end_date=20240702T202216
[2024-07-02T20:22:16.293+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:22:16.414+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:25:37.719+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:25:37.744+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:25:37.749+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:25:37.781+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:25:37.786+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-07-02T20:25:37.804+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpapz5dcdb']
[2024-07-02T20:25:37.829+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask film
[2024-07-02T20:25:38.060+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host e847a37dafab
[2024-07-02T20:25:39.251+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:25:39.253+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:25:39.254+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:25:39.255+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:25:39.307+0000] {logging_mixin.py:188} INFO - <class 'pandas.core.frame.DataFrame'>
[2024-07-02T20:25:39.408+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   9           staff    dvdrental  ...  None  SqlToStaging          None

[1 rows x 15 columns]
[2024-07-02T20:25:39.411+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:25:39.424+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T202537, end_date=20240702T202539
[2024-07-02T20:25:39.473+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:25:39.537+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:33:53.667+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:33:53.685+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:33:53.687+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:33:53.721+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:33:53.738+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-02T20:33:53.772+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpt19do60q']
[2024-07-02T20:33:53.796+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film
[2024-07-02T20:33:53.952+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 99fbc1087931
[2024-07-02T20:33:54.835+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:33:54.864+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:33:54.870+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:33:54.874+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:33:54.956+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SourceDBName'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    print(f"{df['SourceDBName']} \n {df['SourceTableName']} \n {df['SourceSchema']}")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'SourceDBName'
[2024-07-02T20:33:55.002+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T203353, end_date=20240702T203355
[2024-07-02T20:33:55.051+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task film ('SourceDBName'; 93)
[2024-07-02T20:33:55.106+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:33:55.164+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:36:07.820+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:36:07.866+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:36:07.874+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:36:07.907+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:36:07.931+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-02T20:36:07.947+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppp6hrz8j']
[2024-07-02T20:36:07.962+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask film
[2024-07-02T20:36:08.066+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 8ef3b2afa95a
[2024-07-02T20:36:08.359+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:36:08.362+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:36:08.364+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:36:08.367+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:36:09.048+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-02T20:36:09.048+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:36:09.065+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T203607, end_date=20240702T203609
[2024-07-02T20:36:09.122+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:36:09.198+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:40:31.248+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:40:31.367+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:40:31.379+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:40:31.450+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:40:31.464+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-02T20:40:31.499+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2fcmydfu']
[2024-07-02T20:40:31.502+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film
[2024-07-02T20:40:31.721+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host f7a45131ad00
[2024-07-02T20:40:33.141+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:40:33.142+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:40:33.143+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:40:33.144+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:40:33.236+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 29, in some_function
    df = get_data_from_conf_table(table, stage)
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-02T20:40:33.251+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T204031, end_date=20240702T204033
[2024-07-02T20:40:33.298+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task film (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 97)
[2024-07-02T20:40:33.326+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:40:33.347+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:44:45.185+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:44:45.199+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:44:45.203+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:44:45.226+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:44:45.249+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-02T20:44:45.265+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp66u6k4c2']
[2024-07-02T20:44:45.280+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask film
[2024-07-02T20:44:45.424+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 28c1247628aa
[2024-07-02T20:44:46.548+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:44:46.552+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:44:46.556+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:44:46.557+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:film
[2024-07-02T20:44:46.558+0000] {logging_mixin.py:188} INFO - sqltostaging film
[2024-07-02T20:44:46.559+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:44:46.573+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T204445, end_date=20240702T204446
[2024-07-02T20:44:46.626+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:44:46.752+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:47:20.798+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:47:20.814+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:47:20.816+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:47:20.846+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:47:20.855+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-02T20:47:20.857+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp0yf37i0k']
[2024-07-02T20:47:20.865+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask film
[2024-07-02T20:47:21.039+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 0dbf5a897656
[2024-07-02T20:47:21.218+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:47:21.244+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:47:21.245+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:47:21.247+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
TypeError: execute() missing 2 required positional arguments: 'type' and 'schema'
[2024-07-02T20:47:22.163+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T204720, end_date=20240702T204722
[2024-07-02T20:47:22.216+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task film (execute() missing 2 required positional arguments: 'type' and 'schema'; 97)
[2024-07-02T20:47:22.291+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:47:22.325+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:49:58.196+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:49:58.202+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:49:58.207+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:49:58.234+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:49:58.245+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-02T20:49:58.250+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdahmb10o']
[2024-07-02T20:49:58.256+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask film
[2024-07-02T20:49:58.346+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 82e116e15bed
[2024-07-02T20:49:59.275+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:49:59.286+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:49:59.296+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:49:59.297+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film
[2024-07-02T20:49:59.298+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, table)
TypeError: some_function() missing 2 required positional arguments: 'schema' and 'table'
[2024-07-02T20:49:59.347+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T204958, end_date=20240702T204959
[2024-07-02T20:49:59.384+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task film (some_function() missing 2 required positional arguments: 'schema' and 'table'; 88)
[2024-07-02T20:49:59.463+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:49:59.548+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:51:51.242+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:51:51.304+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:51:51.309+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:51:51.397+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:51:51.425+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-02T20:51:51.423+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6b1pi304']
[2024-07-02T20:51:51.448+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film
[2024-07-02T20:51:51.704+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host 910796d1882f
[2024-07-02T20:51:52.861+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:51:52.874+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:51:52.883+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:51:52.889+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film
[2024-07-02T20:51:52.953+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, table)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(table, stage)
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-02T20:51:52.990+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T205151, end_date=20240702T205152
[2024-07-02T20:51:53.021+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task film (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 98)
[2024-07-02T20:51:53.085+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:51:53.114+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:54:17.512+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:54:17.547+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:54:17.556+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:54:17.603+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:54:17.615+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-02T20:54:17.628+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmmrxva5z']
[2024-07-02T20:54:17.637+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask film
[2024-07-02T20:54:17.875+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film scheduled__2024-07-01T00:00:00+00:00 [running]> on host df9727a9ba29
[2024-07-02T20:54:18.771+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:54:18.777+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:54:18.781+0000] {logging_mixin.py:188} INFO - table: film
[2024-07-02T20:54:18.787+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film
[2024-07-02T20:54:18.818+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-02T20:54:18.820+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:54:18.832+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film, execution_date=20240701T000000, start_date=20240702T205417, end_date=20240702T205418
[2024-07-02T20:54:18.870+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:54:18.932+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
